version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/nodejs.dockerfile
    ports:
      - '3000:3000'
    volumes: 
      - logs:/app/logs
      - ./src:/app
      - /app/node_modules
  assignment1:
    build:
      context: .
      dockerfile: dockerfiles/nodejs_as1.dockerfile
    ports:
      - '3001:3001'
    volumes: 
      #- logs:/app/logs
      - ./src_as1:/app
      - /app/node_modules   
  assignment3:
    build:
      context: .
      dockerfile: dockerfiles/nodejs_as3.dockerfile
    ports:
      - '3003:3000'
    volumes: 
      #- logs:/app/logs
      - ./src_as3:/app
      - /app/node_modules    
  npm:
    image: node:14
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./src:/app
volumes: 
  #data:
  logs:
