version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/nodejs.dockerfile
    ports:
      - '3000:3000'
    volumes: 
      - logs:/app/logs
      - ./src:/app
  npm:
    image: node:14
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./src:/app

volumes: 
  #data:
  logs:
